server-name: "unknown"
database:
  # MySQL, MariaDB, H2, SQLite
  type: "H2"
  host: "localhost"
  port: 3306
  user: "root"
  password: "Admin@123"
  name: "matchvault"
  parameters: "?useSSL=false&allowMultiQueries=true"

date:
  format: "yyyy/MM/dd - hh:mm a"
duration:
  include-millisecond: false
  short-format: true

gui:
  global:
    border-item:
      type: "black_stained_glass_pane"
    back-item:
      type: "barrier"
      title: "&4Back"
  match-list:
    title: "&bMatchList"
    previous-item:
      type: "arrow"
      title: "&4Previous"
      slot: 17
    next-item:
      type: "arrow"
      title: "&aNext"
      slot: 44
    placeholders:
      finish:
        if-null: "N/A"
      duration:
        if-null: "N/A"
      status:
        if-won: "&aWin"
        if-lost: "&4Lose"
        if-aborted: "&6Aborted"
    match-item:
      name: "&b%arena_name"
      lore:
        - "&r"
        - "&7Date:"
        - "    &f%date"
        - "&r"
        - "&7Finished:"
        - "    &f%finish"
        - "&r"
        - "&7Duration:"
        - "    &f%duration"
        - "&r"
        - "&7Status: %status"
      type:
        won: "lime_terracotta"
        lost: "red_terracotta"
        on-going: "blue_terracotta"
        aborted: "yellow_terracotta"
  team-list:
    title: "&bTeam List"
    back-item-slot: 0
    placeholders:
      bed-destruction:
        if-null: "N/A"
      elimination:
        if-null: "N/A"
      final-placement:
        if-null: "N/A"
    match-item:
      name: "%team_color%team_name"
      glow-own: true
      lore:
        - "&r"
        - "&7Bed destruction time:"
        - "    &f%bed_destruction_time"
        - "&r"
        - "&7Elimination time:"
        - "    &f%elimination_time"
        - "&r"
        - "&7Final Placement: %final_placement"
  player-list:
    title: "&bPlayer List"
    back-item-slot: 0
    placeholders:
      status:
        if-win: "&aWinner"
        if-lose: "&4Loser"
      own-item: "&7(YOU)"
    match-item:
      name: "%team_color%player_name %own"
      lore:
        - "&7Kills: &f%kills"
        - "&7Final Kills: &f%final_kills"
        - "&7Top Kill Streak: %top_kill_streak"
        - "&7Deaths: &f%deaths"
        - "&7Beds Destroyed: &f%beds_destroyed"
        - "&7Total Irons Collected: &f%resource_iron"
        - "&7Total Golds Collected: &f%resource_gold"
        - "&7Total Diamonds Collected: &f%resource_diamond"
        - "&7Total Emerald Collected: &f%resource_emerald"
        - "&7Spawner Irons Collected: &f%resource_iron_spawner"
        - "&7Spawner Golds Collected: &f%resource_gold_spawner"
        - "&7Spawner Diamonds Collected: &f%resource_diamond_spawner"
        - "&7Spawner Emerald Collected: &f%resource_emerald_spawner"
        - "&7Total Time Played: &f%play_time"
        - "&7Status: %status"




# DO NOT EDIT!
config-version: 1