# Add shared library versions here if needed, e.g.:
[versions]
kotlin = "2.2.20"                  # Kotlin plugin version
zapper = "1.0.3"
shadow = "9.1.0"                   # Shadow plugin version
bukkit-factory = "1.2.0"           # resource-factory plugin version
run-paper = "2.3.1"                # run-task plugin version

spigot = "1.8.8-R0.1-SNAPSHOT"     # Spigot server software version
# bstats = "3.0.2"

# Add shared libraries here if needed, e.g.:
[libraries]
spigot = { module = "org.spigotmc:spigot-api", version.ref = "spigot" }
# bstats = { module = "org.bstats:bstats-bukkit", version.ref = "bstats" }        # bStats library

# Add shared plugins here if needed, e.g.:
[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }                                            # Kotlin JVM plugin
zapper = { id = "io.github.revxrsal.zapper", version.ref = "zapper" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }                                                 # Shadow plugin
bukkit-factory = { id = "xyz.jpenilla.resource-factory-bukkit-convention", version.ref = "bukkit-factory" }     # resource-factory plugin
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run-paper" }                                        # run-task plugin
