# Add shared library versions here if needed, e.g.:
[versions]
kotlin = "2.2.20"                  # Kotlin plugin version
zapper = "1.0.3"
shadow = "9.1.0"                   # Shadow plugin version
bukkit-factory = "1.2.0"           # resource-factory plugin version
run-paper = "2.3.1"                # run-task plugin version

spigot = "1.8.8-R0.1-SNAPSHOT"     # Spigot server software version
bstats = "3.0.2"
mbedwars = "5.5.5"
boostedyaml = "1.3.6"
hikaricp = "7.0.2"
exposed-core = "1.0.0-rc-1"
exposed-jdbc = "1.0.0-rc-1"
mariadb-java-client = "3.5.6"
h2-database = "2.4.240"
triumph-gui = "3.1.13"

# Add shared libraries here if needed, e.g.:
[libraries]
spigot = { module = "org.spigotmc:spigot-api", version.ref = "spigot" }
bstats = { module = "org.bstats:bstats-bukkit", version.ref = "bstats" }        # bStats library
mbedwars = { module = "de.marcely.bedwars:API", version.ref = "mbedwars" }
boostedyaml = { module = "dev.dejvokep:boosted-yaml", version.ref = "boostedyaml" }
hikaricp = { module = "com.zaxxer:HikariCP", version.ref = "hikaricp" }
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed-core" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed-jdbc" }
mariadb-java-client = { module = "org.mariadb.jdbc:mariadb-java-client", version.ref = "mariadb-java-client" }
h2-database = { module = "com.h2database:h2", version.ref = "h2-database" }
triumph-gui = { module = "dev.triumphteam:triumph-gui", version.ref = "triumph-gui" }

# Add shared plugins here if needed, e.g.:
[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }                                            # Kotlin JVM plugin
zapper = { id = "io.github.revxrsal.zapper", version.ref = "zapper" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }                                                 # Shadow plugin
bukkit-factory = { id = "xyz.jpenilla.resource-factory-bukkit-convention", version.ref = "bukkit-factory" }     # resource-factory plugin
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run-paper" }                                        # run-task plugin
